name: Deployment with CI+CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
#     - name: Test with pytest
#       run: |
#         make test
    - name: Format code
      run: |
        make format
  
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://burnished-ember-328422.nw.r.appspot.com/prediction
    steps:
      - name: Deploy
        run: echo I am deploying! 
  
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: https://burnished-ember-328422.nw.r.appspot.com
    steps:
      - name: Deploy
        run: echo I am deploying!
      - name: Install dependencies
        working-directory: /GoogleCloudApp/userinterface
        run: npm install
    
      - name: Run the tests
#         working-directory: /GoogleCloudApp/userinterface
        run: npm test
      - name: Build
#         working-directory: /GoogleCloudApp/userinterface
        run: npm run build
        
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://burnished-ember-328422.nw.r.appspot.com
    steps:
      - name: Deploy
        run: echo I am deploying! 
